server:
  port: 8080

app:
  api-prefix: /api/v1


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=${app.api-prefix}/product-service/**
          filters:
            - StripPrefix=3

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=${app.api-prefix}/user-service/**
          filters:
            - StripPrefix=3

    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1509/eureka/