spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_product_service_db
    username: root
    password: 123456@
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081
  servlet:
    context-path: /api/product-service

